### ISSUE TITLE
About the evaluation of the method

### ISSUE THREAD

**Issue by GH-HOME** [yqueau/near_ps#1]
I found that only qualitative results are provided in the implementation, such as the output obj file. However, is there any way to test it quantitively? 
Actually, I try a synthetic sphere case under near-light setting, the normal angular error is 3-4 degree, is that correct?

**Comment by GH-HOME** [comment]
I notice that there is a file named "ground_truth.ply" in "Statuette_GT" folder. But how to measure the distance between this GT point sets and the estimated 3D point positions.

**Comment by yqueau** [comment]
Hi, 

For the statuette, we indeed provide a grount truth point cloud obtained using a laser scanner, for quantitative evaluation purpose. This was used to produce, e.g., the histogram in Fig 17 in the JMIV paper. 

To do so, we exported our 3D-reconstruction as an OBJ, then aligned the ground truth and our 3D-reconstruction using CloudCompare, first roughly be selecting a few matching points, and then iteratively using ICP. Then we computed the cloud to cloud distance. 

As for the question on synthetic sphere, if the images match the model then you should obtain a mean angular error of zero. Maybe a parameter is not set appropriately ? I can have a look next week if that can help. 

Regards, 
Yvain
